import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "common/boolean": "src/validators/common/boolean.ts",
    "common/date": "src/validators/common/date.ts",
    "common/datetime": "src/validators/common/datetime.ts",
    "common/email": "src/validators/common/email.ts",
    "common/file": "src/validators/common/file.ts",
    "common/id": "src/validators/common/id.ts",
    "common/number": "src/validators/common/number.ts",
    "common/password": "src/validators/common/password.ts",
    "common/text": "src/validators/common/text.ts",
    "common/time": "src/validators/common/time.ts",
    "common/url": "src/validators/common/url.ts",
    "common/credit-card": "src/validators/common/credit-card.ts",
    "common/ip": "src/validators/common/ip.ts",
    "common/color": "src/validators/common/color.ts",
    "common/coordinate": "src/validators/common/coordinate.ts",
    "taiwan/business-id": "src/validators/taiwan/business-id.ts",
    "taiwan/national-id": "src/validators/taiwan/national-id.ts",
    "taiwan/mobile": "src/validators/taiwan/mobile.ts",
    "taiwan/postal-code": "src/validators/taiwan/postal-code.ts",
    "taiwan/tel": "src/validators/taiwan/tel.ts",
    "taiwan/fax": "src/validators/taiwan/fax.ts",
    "taiwan/invoice": "src/validators/taiwan/invoice.ts",
    "taiwan/license-plate": "src/validators/taiwan/license-plate.ts",
    "taiwan/bank-account": "src/validators/taiwan/bank-account.ts",
    "taiwan/passport": "src/validators/taiwan/passport.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  splitting: true,
})
